### ISSUE TITLE
Make python bindings for op-level symbol substitution

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1014]
At least for `CircBox`; if easy we should make it work for all op types.

**Comment by trvto** [comment]
@cqc-alec I think I need some more info. What exactly is needed here?:

- Expose `Op.symbol_substitution(...)` in pytket?
  - substitution in-place? (is that even possible?) Or returns new op with symbols substituted? (currently how `op->symbol_substitution(...)` works in TKET.
- Allow in-place substitution in circuit for user chosen list of OpTypes?
- Something else?

**Comment by cqc-alec** [comment]
It sounds like the request is for an in-place `CircBox.symbol_substitution()`.
