### ISSUE TITLE
`CliffordSimp` produces circuit inequivalent to input

### ISSUE THREAD

**Issue by fuglede** [CQCL/tket#1020]
Say I have the following circuit:

```python
from pytket.extensions.qiskit import qiskit_to_tk, tk_to_qiskit
from qiskit import QuantumCircuit

circ = QuantumCircuit(2)
circ.x(0)
circ.cnot(0, 1)
circ.cnot(1, 0)
circ.draw()

#      ┌───┐     ┌───┐
# q_0: ┤ X ├──■──┤ X ├
#      └───┘┌─┴─┐└─┬─┘
# q_1: ─────┤ X ├──■──
#           └───┘     
```

If I apply `CliffordSimp` to this, I get the following result:
```python
from pytket.passes import CliffordSimp

c = qiskit_to_tk(circ)
CliffordSimp().apply(c)
tk_to_qiskit(c).draw()

# global phase: π/2
#      ┌───────────────┐┌───┐
# q_0: ┤ U(π,-π/2,π/2) ├┤ X ├
#      └───────────────┘└─┬─┘
# q_1: ───────────────────■──
```

I would have expected the resulting circuit to be operator equivalent -- or at least statevector equivalent -- to the input circuit up to global phase, but neither is the case. Am I missing something?

**Comment by yao-cqc** [comment]
Hi @fuglede, in this case the CliffordSimp pass added a implicit SWAP to reduce the number of CXs. `c.implicit_qubit_permutation()` will show you this information. You can also call CliffordSimp with the allow_swaps option set to False to disable this behaviour.

**Comment by fuglede** [comment]
Thanks @yao-cqc, that makes sense. For Qiskit transpiler passes, the corresponding information would be part of `QuantumCircuit.layout` (and `QuantumCircuit.layout.final_layout` in particular); might it be helpful to add this information under `tk_to_qiskit`?

**Comment by yao-cqc** [comment]
Thank you @fuglede for the suggestion! We will look into ways to add this information when doing the conversion. Looks like a similar issue has already been raised in [pytket-qiskit](https://github.com/CQCL/pytket-qiskit/issues/123).

**Comment by fuglede** [comment]
Gotcha, yep, that one completely covers what I had in mind in the previous comment as well.

**Comment by fuglede** [comment]
And should one expect operator equivalence or only statevector equivalence? From my experience, I only get the latter, but the former would be useful for optimizing subcircuits, so if there's a way to require that level of equivalence, that would be nice.
