### ISSUE TITLE
Add `DecomposeSwapsToCXs` or `KAKDecomposition` to post-routing optimizations in default passes.

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#103]
(Depending on the optimization level.)

See the discussion on #25 .

**Comment by CalMacCQ** [comment]
All of the TKET supported backends for superconducting devices now have a pass sequence that is consistent with pytket-qiskit

https://tket.quantinuum.com/extensions/pytket-qiskit/#default-compilation

I ran some more benchmarks of these post-routing optimisations a couple of months ago and I noticed an improvement in CZ count/depth of about 5% which seems pretty consistent with what Will disucssed in the linked thread.
