### ISSUE TITLE
API docs for `ConjugationBox` missing

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1066]
There are [docs](https://cqcl.github.io/tket/pytket/api/circuit_class.html#pytket.circuit.Circuit.add_conjugation_box) for `add_conjugation_box` but not for `ConjugationBox` itself.

**Comment by CalMacCQ** [comment]
Weird..

If I build the docs locally with pytket 1.20.1 I seem to be able to see it.

![Screenshot 2023-10-05 at 16 38 50](https://github.com/CQCL/tket/assets/93673602/ea1f6f85-3169-4dc7-bec5-060588405a76)

**Comment by cqc-alec** [comment]
That is strange.

**Comment by CalMacCQ** [comment]
Any ideas @yao-cqc ?

**Comment by cqc-alec** [comment]
Ah, thanks Yao, we can close this then.
