### ISSUE TITLE
Stubs contains invalid type `Dict[List[bool], ...]`

### ISSUE THREAD

**Issue by yao-cqc** [CQCL/tket#1067]
Lists are not hashable hence cannot be used as dictionary keys.

There are several cases in `circuit.pyi`, e.g.

```python
class MultiplexedU2Box(Op):
    @overload
    def __init__(self, op_map: Dict[List[bool],Op], impl_diag: bool = ...) -> None: ...
```

It should be `Dict[Tuple[bool],Op]`

**Comment by trvto** [comment]
Not as easy do as you would think, but I've put in a PR #1072
