### ISSUE TITLE
Branch protection rules prevent PRs that don't change tket or pytket from being merged

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1115]
The issue is the "build and test pytket (macos)" job, which is required, and should be skipped in such cases. For some reason, while the job is not run, the PR does not show it as skipped but as waiting for a runner (indefinitely), preventing merging.

For an example see this PR: #1114 .

**Comment by cqc-alec** [comment]
Required status checks:
![image](https://github.com/CQCL/tket/assets/54802828/10b9ed8c-3593-4e64-a9a8-275fe24c493e)

**Comment by trvto** [comment]
This happens because some weird naming stuff when you use the `matrix` strategy. There is already a workaround implemented for the `tket` build. See job `build_test_tket_not_required`. If you add something similar for the pytket macos builds, should work.

**Comment by trvto** [comment]
Another possibility to fix this (which I personally find better) is to add a job at the end of the workflow file that fails if any other job fails. See https://github.com/CQCL/pytket-aqt/blob/develop/.github/workflows/tests.yml#L101 for an example. If you have such a job, you can configure github to only have it as a required check. Which makes things a lot nicer I think
