### ISSUE TITLE
pytket build fails unknown warning group '-Wambiguous-reversed-operator' 

### ISSUE THREAD

**Issue by Huangyunqi** [CQCL/tket#1249]
My MacOS is Mojave 10.14.6. I follow the instruction to build pytket. I have tried python 3.10 and python 3.11. But when I run conan create tket --user=tket --channel=stable --build=missing -o "boost/*":header_only=True -o "tklog/*":shared=True -o "tket/*":shared=True -tf "", it said: 

/Users/.conan2/p/b/tket5799bbf9136b1/b/include/tket/Utils/Symbols.hpp:21:32: error: 
      unknown warning group '-Wambiguous-reversed-operator', ignored
      [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wambiguous-reversed-operator"

1 error generated.
make[2]: *** [CMakeFiles/tket.dir/src/Utils/PauliTensor.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/tket.dir/src/Utils/CosSinDecomposition.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/tket.dir/src/Utils/MatrixAnalysis.cpp.o] Error 1
make[1]: *** [CMakeFiles/tket.dir/all] Error 2
make: *** [all] Error 2

tket/1.2.89@tket/stable: ERROR: 
Package '6ff618a2bc33e5da6d95a6748a20dab7b8c3763f' build failed
tket/1.2.89@tket/stable: WARN: Build folder /Users/.conan2/p/b/tket5799bbf9136b1/b/build/Release
ERROR: tket/1.2.89@tket/stable: Error in build() method, line 98
	cmake.build()
	ConanException: Error 2 while executing

How to do that?

**Comment by Huangyunqi** [comment]
> Hi, thanks for the report. What version of clang are you building with? MacOS 10 is pretty old (in fact, pytket is only officially supported on MacOS >= 12), and it may be that the version of clang is too old.

Thank you for your reply. I followed the instructions and successfully installed clang-14 by MacPorts. When use clang --version, it shows that the version of clang is 11.0.0. Is it because the compile command cannot select the installed clang-14 version?

**Comment by cqc-alec** [comment]
Maybe you could try setting `compiler.version=14` in your conan profile (you can find the path to this file using `conan profile path default`).
