### ISSUE TITLE
Misinterpretation of Classical Conditions and User-defined Gates in `circuit-from/to-qasm-str`

### ISSUE THREAD

**Issue by p51lee** [CQCL/tket#1299]
### Overview
The functions `circuit_from_qasm_str` and `circuit_to_qasm_str` improperly process classical conditions applied to user-defined gates when importing OpenQASM programs. Specifically, it fails to maintain the classical condition for each component gate within a user-defined gate that encompasses multiple operations.

### Example and reproduction steps

Consider the following Python code that utilizes `circuit_from_qasm_str` to import a QASM string:

```python
from pytket.qasm import circuit_from_qasm_str, circuit_to_qasm_str

circ_qasm = """OPENQASM 2.0;
include "qelib1.inc";
gate cx_o0 q0,q1 { x q0; cx q0,q1; x q0; }
qreg q[2];
creg c[1];
if(c==1) cx_o0 q[1],q[0];
measure q[0] -> c[0];"""

circ = circuit_from_qasm_str(circ_qasm)
print(circuit_to_qasm_str(circ))
```
#### Observed Output
```qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[1];
if(c==1) x q[1];
cx q[1],q[0];
x q[1];
measure q[0] -> c[0];
```

#### Expected Behavior
The classical condition `if (c==1)` should be applied to each sub-gate within the custom gate `cx_o0`, resulting in the following correct output:
```qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[1];
if(c==1) x q[1];
if(c==1) cx q[1],q[0];
if(c==1) x q[1];
measure q[0] -> c[0];
```

**Comment by cqc-alec** [comment]
Thank you for the report. Looking into this now...
