### ISSUE TITLE
Missing Gate Definition for ECR in QASM Export

### ISSUE THREAD

**Issue by p51lee** [CQCL/tket#1302]
### Overview

The `ECR` gate, not present in the [qelib.inc](https://github.com/Qiskit/qiskit/blob/main/qiskit/qasm/libs/qelib1.inc) library, is exported via `circuit_to_qasm_str` without the requisite gate definition. This omission results in an incomplete and potentially non-executable QASM output.

### Example and reproduction steps

Consider the following Python code:

```python
import pytket
from pytket.qasm import circuit_to_qasm_str

circ = pytket.Circuit(2, 1)
circ.ECR(0, 1)
print(circuit_to_qasm_str(circ))
```
#### Observed
The exported QASM code lacks an explicit definition for the `ECR` gate, as shown below:
```qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[1];
ecr q[0],q[1];
```

#### Expected
An additional gate definition corresponding to the `ECR` gate should be included, similar to how Qiskit handles such exports as shown below:
```qasm
...
gate rzx_4748764848(_gate_p_0) _gate_q_0, _gate_q_1 {
  h _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(pi/4) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  h _gate_q_1;
}
gate rzx_4748764896(_gate_p_0) _gate_q_0, _gate_q_1 {
  h _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/4) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  h _gate_q_1;
}
gate ecr _gate_q_0, _gate_q_1 {
  rzx_4748764848(pi/4) _gate_q_0, _gate_q_1;
  x _gate_q_0;
  rzx_4748764896(-pi/4) _gate_q_0, _gate_q_1;
}
...
```

**Comment by p51lee** [comment]
Additionally, I found the same issues with the `cs` and `csdg` gates.

**Comment by cqc-alec** [comment]
Thanks for the report (and the others!) Will take a look.
