### ISSUE TITLE
How to translate a Graph into a quantum circuit again

### ISSUE THREAD

**Issue by VicentePerezSoloviev** [CQCL/tket#1330]
Tket propides a function for moving a quantum circuit into a networkx graph as this:

`graph = Graph(circuit).as_nx()`

However, is there any way to to do it in the other way around? Given a graph, translate it into a quantum circuit. I have deeply checked all the documentation and did not found any valid function for this. Thank in advance.

**Comment by cqc-alec** [comment]
There isn't a readymade method to do this. I think it should be fairly straightforward to reconstruct the circuit from the graph, starting by doing a topological sort and then walking through it adding commands corresponding to the nodes and edges. You may lose some information though, like register names which I don't think are preserved in the graph.
