### ISSUE TITLE
Please add CnRz and CnRx gates

### ISSUE THREAD

**Issue by markgjackson** [CQCL/tket#1346]
There is already a CnRy gate but for a project I am working on I will also need CnRz, thank you.

**Comment by cqc-alec** [comment]
Note that you can get CnRz by placing (H;S) on the target qubit before the CnRy and (Sdg;H) on the target qubit after it.

**Comment by markgjackson** [comment]
Hi Alec, thank you and yes that is precisely what I am doing now but I thought it would be more efficient to have it be directly implemented, and also when I generate the circuit diagram it would be nice to have the gate listed directly

**Comment by cqc-alec** [comment]
It wouldn't be any more efficient since when we decompose to native gates we'd get exactly the same decomposition. But I agree it would look nicer on a circuit diagram.

**Comment by sjdilkes** [comment]
These gates have been added with https://github.com/CQCL/tket/pull/1405 and will be available in the next pytket release.
