### ISSUE TITLE
Updating `lark-parser` depedency to `lark`

### ISSUE THREAD

**Issue by nquetschlich** [CQCL/tket#1356]
Hi,

I am using `pytket` in a project where also `lark` is an dependency additionally to `lark-parser` that is required by `pytket`. Here, I face some compatibility issues resulting in errors since apparently having both `lark` and `lark-parser` installed with different versions is problematic. 

Therefore, I was wondering whether the (apparently deprecated) `lark-parser` dependency could be upgraded to `lark` as well.

**Comment by cqc-alec** [comment]
Hi Nils, this task has been on our backlog for a while -- it's not entirely straightforward as the API has changed and it requires some code rewrites. Can't promise, but we'll try and prioritise it for the next release.
