### ISSUE TITLE
Clean up `pytket.circuit.OpType` page

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/tket#1406]
The layout of the `OpType` documentation is far from ideal. 
https://tket.quantinuum.com/api-docs/optype.html

Maybe we could have a nice table layout with the gate names. Perhaps even circuit diagrams for each the OpTypes?

There is some awkward indentaton here that causes Some of the `OpType.AAMS` definition doesn't fit on the page.

The source file for this page is a header file currently rather than rst. Maybe this would be an issue for some of the nicer sphinx formatting.

**Comment by cqc-alec** [comment]
Closing this as the description is very general. Feel free to make new issues for specific changes.
