### ISSUE TITLE
Investigate potential CMake improvements

### ISSUE THREAD

**Issue by jake-arkinstall** [CQCL/tket#1482]
At the moment, dependant projects need to find and link Eigen3 in order to link `tket::tket`, because:

- public-facing headers depend on eigen headers.
- eigen is linked privately in CMakeLists.txt

Ideally, tket/test/CMakeLists.txt should build by linking only tket and catch2, and having cmake transitively include the dependencies of tket.

**Comment by jcqc** [comment]
Closing as won't do.
