### ISSUE TITLE
Quantum circuit with conditionals can cause RunTime error 

### ISSUE THREAD

**Issue by IlanIwumbwe** [CQCL/tket#1536]
[Benny](https://github.com/Bennybenassius) and I found this by running a randomly generated circuit through the compiler.

Recreate with:
``` Python
main_circ = Circuit(2, 2, "main_circ")
a = Symbol("a")
s_map = {a : -0.5}

# Adding creg resources 
creg_0 = main_circ.add_c_register("creg_0",2)

main_circ.Rz(1,0, condition = reg_eq(creg_0, 3))
main_circ.symbol_substitution(s_map)

main_circ.measure_all()
```
Results in:
``` Python
AttributeError: 'pytket._tket.circuit.ClassicalOp' object has no attribute 'lower'
```

When we remove the symbol substitution, the code runs. After closer inspection, we found that symbol substitution changes `Optype.RangePredicate` ops into `Optype.ClassicalOp` even though optype is still stated as `Optype.RangePredicate` [here](https://github.com/CQCL/pytket-qiskit/blob/main/pytket/extensions/qiskit/qiskit_convert.py#L653-#L655)

**Comment by cqc-alec** [comment]
Is the above the full code to reproduce? Running it works for me without error.

**Comment by IlanIwumbwe** [comment]
No, here is the updated code snippet:
``` Python
main_circ = Circuit(2, 2, "main_circ")
a = Symbol("a")
s_map = {a : -0.5}

# Adding creg resources 
creg_0 = main_circ.add_c_register("creg_0",2)

main_circ.Rz(1,0, condition = reg_eq(creg_0, 3))
main_circ.symbol_substitution(s_map)

main_circ.measure_all()

backend = AerBackend()
no_pass_circ = backend.get_compiled_circuit(main_circ, optimisation_level=0)
counts = backend.run_circuit(no_pass_circ).get_counts()
```

**Comment by IlanIwumbwe** [comment]
Ah, that makes sense. Thank you for the quick response.

**Comment by cqc-alec** [comment]
> Ah, that makes sense. Thank you for the quick response.

Thank you for raising the issue. Will work on a fix.
