### ISSUE TITLE
QASM Conversion Error with `ClassicalExpBox` inside `CircBox`

### ISSUE THREAD

**Issue by sjdilkes** [CQCL/tket#1541]
`circuit_to_qasm_str` can incorrectly introduce "default" `Bit` (i.e. `Bit` labelled "c") when handling `ClassicalExpBox`:
```
inner_c: Circuit = Circuit(0)

work_bits: List[Bit] = [Bit("w_bit", i) for i in range(3)]
condition_bit: Bit = Bit("condition_bit", 0)

for b in work_bits + [condition_bit]:
    inner_c.add_bit(b)
inner_c.add_classicalexpbox_bit(
    work_bits[0] ^ work_bits[1] ^ work_bits[2],
    [condition_bit]
)

print("Inner QASM Block - looks correct:\n", circuit_to_qasm_str(inner_c,  header="hqslib1"))

outer_c: Circuit = Circuit()
for b in work_bits + [condition_bit]:
    outer_c.add_bit(b)

outer_c.add_circbox(
    CircBox(inner_c),
    inner_c.bits
)


# It produces incorrect QASM regardless of whether the Box is decomposed
# DecomposeBoxes().apply(outer_c)
print("Outer QASM Block - looks incorrect:\n", circuit_to_qasm_str(outer_c, header="hqslib1"))

# Note that the circuit commands look fine when comparing after decomposing the box:
DecomposeBoxes().apply(outer_c)
for inner, outer in zip(inner_c, outer_c):
    assert inner == outer

**Comment by cqc-alec** [comment]
Another way to demonstrate (probably) the same bug:

```python
def make_circ():
    c = Circuit()

    work_bits: List[Bit] = [Bit("w_bit", i) for i in range(3)]
    condition_bit: Bit = Bit("condition_bit", 0)

    for b in work_bits + [condition_bit]:
        c.add_bit(b)
    c.add_classicalexpbox_bit(
        work_bits[0] ^ work_bits[1] ^ work_bits[2], [condition_bit]
    )
    return c


c0 = make_circ()
c1 = make_circ()

assert c0 == c1 # OK

CircBox(c1) # somehow this is modifying c1

assert c0 == c1 # fails
```

The names of the bits inside the `ClassicalExpBox` in `c1` have been changed from `w_bit` to `c`.

**Comment by sjdilkes** [comment]
This problem is similar to https://github.com/CQCL/tket/issues/1544.

When writing `pytket` `ClassicalExpBox` to `qasm`, the `expr` object is converted to a string to define the logical expression over bits: https://github.com/CQCL/tket/blob/2936a367daed02faab6ba73a85c10e1cf0a60606/pytket/pytket/qasm/qasm.py#L1689

When adding a `Circuit` to a `CircBox`, the `flatten_registers` method is applied to the `Circuit`. As per https://github.com/CQCL/tket/issues/1544, `flatten_registers` will call `rename_units`, which has additional handling for `ClassicalExpBox` to re-label the arguments of the `expr` object to match the renamed units of the Circuit, i.e. in this case to the default `c` register.

When a `CircBox` is then added to a `Circuit`, no extra handling is run to re-convert the arguments of the `expr` to match the circuit. 

This is fine when we look at the `Command` of a circuit, because we don't see the expression we just see the correct `Bit`. However, when we look at the output `qasm` as above, the `str(expr)` is use to write the action, and this still has the expression updated as being for the `c` register. I think this will be the same problem in the `pytket-phir` repository with running these circuits on the local emulator, see:
https://github.com/CQCL/pytket-phir/blob/ddd40190020424b4c56960a4ead227ff845f4856/pytket/phir/phirgen.py#L407.


I see a couple of solutions. The first is to assume that the `expr` held in a `ClassicalExpBox` just details some relationship between input bits, which can be represented by any labelling, but that we always re-label the `expr` to match the `Bit` being input to the `Command` when lowering, such as with `QIR` gen, `QASM` gen and `PHIR` gen.

The second is to always guarantee that the `ClasscialExpBox` `expr` arguments match the inputs to the command as tracked from the boundary of the circuit. 

To do the second option we need to update the `add_gate` style methods in:
https://github.com/CQCL/tket/blob/2936a367daed02faab6ba73a85c10e1cf0a60606/pytket/binders/circuit/Circuit/add_op.cpp 
to relabel `expr` in `ClassicalExpBox`, and recursively `ClassicalExpBox` inside `CircBox` (.. inside `CircBox`). We also need to then update the `rename_units` method to check all `CircBox` for `ClassicalExpBox` that need their expressions updated.


What do you think?

**Comment by cqc-alec** [comment]
> The first is to assume that the expr held in a ClassicalExpBox just details some relationship between input bits, which can be represented by any labelling, but that we always re-label the expr to match the Bit being input to the Command when lowering, such as with QIR gen, QASM gen and PHIR gen.

We'll go with this solution. Needs:
* update to documentation of `ClassicalExpBox` (in tket and pytket) to clarify this;
* update to QASM conversion functions (in pytket);
* update to PHIR conversion function (in pytket-phir).

**Comment by cqc-alec** [comment]
However, I am now wondering if we should radically rewrite `LogicExp`  and `ClassicalExpBox`. Storing the names of the arguments as an integral part of the expression seems like a design flaw.

**Comment by sjdilkes** [comment]
I started implementing this today and found additional issues related to the `arguments` in `LogicExp` being a mixture of `Bit`, `BitRegister`, `bool` and `int`, while input wires in the circuit vertex correspond to `Bit`. I would lean towards the radical rewrite option, as the only solution I can see for this now is case switching on the `type` of arguments in `LogicExp` and matching up to input wires to the vertex, which is starting to become excessively complicated.

**Comment by cqc-alec** [comment]
This issue goes away if we replace the lines
```python
inner_c.add_classicalexpbox_bit(
    work_bits[0] ^ work_bits[1] ^ work_bits[2],
    [condition_bit]
)
```
with
```python
inner_c.add_clexpr(
    WiredClExpr(
        expr=ClExpr(op=ClOp.BitXor, args=[ClBitVar(0), ClBitVar(1), ClBitVar(2)]),
        bit_posn={0: 0, 1: 1, 2: 2},
        output_posn=[3],
    ),
    work_bits + [condition_bit],
)
```
We should begin deprecation of `ClassicalExpBox` and add warnings to the method `add_classicalexpbox_bit()` (and similar methods) that they are buggy, advising people to sue `add_clexpr()` instead.
