### ISSUE TITLE
nix builds on CI failing

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1635]
Seems they aren't using the latest version of mypy.

**Comment by jake-arkinstall** [comment]
I've wanted to do a `nix flake update` for a while so that should fix it.

Do you have a preference as to which python version should be the default when built with nix?

**Comment by cqc-alec** [comment]
> I've wanted to do a `nix flake update` for a while so that should fix it.
> 
> Do you have a preference as to which python version should be the default when built with nix?

No particular preference, maybe 3.12 would be safest?

The mypy version used is always the latest on pipy, currently 1.13.0.
