### ISSUE TITLE
Using `circuit.bits` as `args` to `add_wasm` with more registers causes a `Fatal Python error`.

### ISSUE THREAD

**Issue by johnchildren** [CQCL/tket#1641]
Using a test case like this in `test_classical.py` 

```python
def test_wasm_circuit_bits() -> None:
    w = wasm.WasmFileHandler("testfile.wasm")
    c = Circuit(0, 6)
    c.add_wasm("add_one", w, [1], [1], c.bits)
    assert c.depth() == 1
```

Results in an error during the tests of:

```
classical_test.py ................[2024-10-29 15:13:09] [tket] [critical] Assertion 'sum_of_i32 == n_' (/build/tket-sources/src/Ops/ClassicalOps.cpp : WASMOp : 266) failed>
Fatal Python error: Aborted

Current thread 0x00007ffff7f8f740 (most recent call first):
  File "/nix/store/sldmq9pa6aw0plb54q6lc9maydx6a35k-python3.12-pytket-1.34.0/lib/python3.12/site-packages/pytket/circuit/__init__.py", line 103 in overload_add_wasm
  File "/build/test_root/tests/classical_test.py", line 363 in test_wasm_circuit_bits
```

Not that reducing the number of classical registers in the circuit or using a different `args` avoids this issue.

**Comment by johnchildren** [comment]
You can also trigger this bug with:

```python
def test_wasm_circuit_bits() -> None:
    w = wasm.WasmFileHandler("testfile.wasm")
    c = Circuit(0, 1)
    c.add_wasm("add_one", w, [1], [1], [0])
    assert c.depth() == 1

```

**Comment by cqc-alec** [comment]
I noticed recently that the unit ID we use for the wasm state (which has the special name `_w`) has type `Bit`, which seems wrong. Could this be related @cqc-melf ?

**Comment by cqc-alec** [comment]
> [@cqc-alec](https://github.com/cqc-alec) I have taken a look on this, it should have the type WasmState, see
> 
> [tket/tket/include/tket/Utils/UnitID.hpp](https://github.com/CQCL/tket/blob/a9add4b7986a255cc3fdf90dc17aaa3d85379c7b/tket/include/tket/Utils/UnitID.hpp#L229)
> 
> Line 229 in [a9add4b](/CQCL/tket/commit/a9add4b7986a255cc3fdf90dc17aaa3d85379c7b)
>  class WasmState : public UnitID { 
> 
> Can you give some more details where you have seen this? I was not able to construct an example where this did not work.

In [this test](https://github.com/CQCL/tket/blob/a9add4b7986a255cc3fdf90dc17aaa3d85379c7b/pytket/tests/classical_test.py#L181), if you insert the lines

```python
    cmd = c.get_commands()[0]
    for arg in cmd.args:
        print(arg, type(arg))
```

after constructing the circuit, and run it with `pytest -s`, you see:

```
c[0] <class 'pytket._tket.unit_id.Bit'>
c[1] <class 'pytket._tket.unit_id.Bit'>
_w[0] <class 'pytket._tket.unit_id.Bit'>
```

(This was the reason for [this workaround](https://github.com/CQCL/tket/blob/a9add4b7986a255cc3fdf90dc17aaa3d85379c7b/pytket/pytket/circuit/decompose_classical.py#L364).)

**Comment by cqc-melf** [comment]
> Is the issue that there is no python binding for the `WasmState` class? Should it even have a python binding?

Probably yes, still unexpected that they show up as bits. I will add them.
