### ISSUE TITLE
Add Support for manylinux2014 Wheels (glibc 2.17 Compatibility)

### ISSUE THREAD

**Issue by kinianlo** [CQCL/tket#1650]
### Description
pytket currently lacks wheel support for manylinux2014, which would ensure compatibility with systems running glibc 2.17 (e.g., CentOS 7 which is still used in some HPC clusters). The last version of pytket with manylinux2014 support was 1.22.0, while the latest version of lambeq requires pytket >= 1.31.0.

### Requested Solution:
Update the build pipeline to produce manylinux2014-compatible wheels if feasible.
Adding manylinux2014 wheels would simplify installation for a broader range of users in enterprise and older Linux environments.

**Comment by cqc-alec** [comment]
Hi, thanks for your request. We don't plan to provide pre-built wheels for manylinux2014 anymore. It should however be possible to build them locally, by following the steps in the build script [here](https://github.com/CQCL/tket/blob/main/.github/workflows/linuxbuildwheel).
