### ISSUE TITLE
Add documentation for `ClExprOp`

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket#1654]
The new op is mentioned in the changelog for `1.34.0`, but it does not appear [in the docs](https://tket.quantinuum.com/api-docs/search.html?q=ClExprOp&check_keywords=yes&area=default).

**Comment by aborgna-q** [comment]
The box also does not appear in the [json schema](https://github.com/CQCL/tket/blob/develop/schemas/circuit_v1.json).

**Comment by cqc-alec** [comment]
Didn't mean to close this (TIL that "see" is also an issue-closing keyword). JSON schema still to add, so reopening.
