### ISSUE TITLE
OutcomeArray handling producing unexpected numpy types with numpy 2

### ISSUE THREAD

**Issue by ss2165** [CQCL/tket#1677]
code: 

```python
from pytket.extensions.qiskit import AerBackend
from pytket import Circuit
print(AerBackend().run_circuit(Circuit(1).measure_all(), 10).get_counts())
```
Outputs:
With numpy 1.26.4:

```python
Counter({(0,): 10})
```

With numpy 2.1.3:

```python
Counter({(np.uint8(0),): np.int64(10)})
```

**Comment by CalMacCQ** [comment]
Minor comment. 

I added a workaround to the quantum phase estimation example notebook -> https://docs.quantinuum.com/tket/user-guide/examples/algorithms_and_protocols/phase_estimation.html

See the the `tuple_to_str` function which avoids label clashing on the x-axis of the results plot

**Comment by cqc-alec** [comment]
Actually we were producing the same types in numpy 1, but never noticed because they were rendered differently.

In numpy 1, `repr(numpy.uint8(1))` is `1`; in numpy 2 it is `np.uint8(1)`.
