### ISSUE TITLE
Improve performance of `CliffordReductionPass`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1696]
This seems to be a bottleneck in `FullPeepholeOptimise`. According to the attached profiling graph, at least on x86_64 the bottleneck is the call to `Circuit::index_map()` in `CliffordReductionPass::search_back_for_match()`.
![Image](https://github.com/user-attachments/assets/9dbd3c03-1eda-427b-baab-8b85a58909dd)

**Comment by johnchildren** [comment]
It seems like it's something to do with this IndexMap here (a std::unordered_map) https://github.com/CQCL/tket/blob/a5f31694510209486999c7186c68a22e08671402/tket/src/Circuit/Circuit.cpp#L134

Two questions about it:

1. Does it need to be recomputed every time search_back_for_match is called?
2. Is is possible to guess how large IndexMap will be ahead of time from the size of the DAG such that https://en.cppreference.com/w/cpp/container/unordered_map/reserve can be called ahead of time to avoid rehashing?
