### ISSUE TITLE
Support `rxx` gate for `pytket_qasm`.

### ISSUE THREAD

**Issue by vtomole** [CQCL/tket#189]
Before working on adding this, I need confirmation from the maintainers that this is what would like.

Qiskit has a native [rxx gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RXXGate.html) but Pytket's QASM parer can't parse it because `rxx` hasn't been added to [this list ](https://github.com/CQCL/tket/blob/ded37ab58176d64117a3e11e8a667ce0199a338a/pytket/pytket/qasm/qasm.py#L71). This issue is to track whether or not we should add it. 

**How to reproduce**
```python
from pytket.qasm import circuit_from_qasm, circuit_to_qasm_str
import tempfile, os

fd, path = tempfile.mkstemp(".qasm")
os.write(fd, """OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
rxx(pi/2) q[0],q[1];
measure q -> c;
""".encode())
os.close(fd)
circ = circuit_from_qasm(path)
os.remove(path)
```

Throws
```
TypeError: Cannot parse gate of type: rxx
```

but it works in Qiskit
```python
import qiskit

circ = qiskit.QuantumCircuit.from_qasm_str("""OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
rxx(pi / 2) q[0],q[1];
measure q -> c;
""")
```

**Comment by cqc-alec** [comment]
Thanks for raising this. It looks like qiskit's rxx is exactly pytket's [OpType](https://cqcl.github.io/tket/pytket/api/optype.html).XXPhase (with the usual factor pi applied to the parameter). So this should be straightforward to add. If you are happy to make a PR for this then please go ahead!

**Comment by vtomole** [comment]
Thank you for the prompt response. I've opened a pull request https://github.com/CQCL/tket/pull/190

**Comment by vtomole** [comment]
Closed by https://github.com/CQCL/tket/pull/190
