### ISSUE TITLE
More intelligent handling of SWAP gates in synthesis passes

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#25]
Routing introduces SWAP gates; when followed by synthesis passes these are often decomposed to sequences of CX gates. The CX sequence may depend on the order of qubits in the SWAP, and this can have an effect on cancellation.

For example:
```python
from pytket import Circuit, OpType
from pytket.passes import SynthesiseTket


def synthesise(c):
    SynthesiseTket().apply(c)
    print(c.get_commands())


circ0 = Circuit(2).CX(0, 1).SWAP(0, 1)
circ1 = Circuit(2).CX(0, 1).SWAP(1, 0)

synthesise(circ0)
synthesise(circ1)
```
outputs:
```
[CX q[1], q[0];, CX q[0], q[1];]
[CX q[0], q[1];, CX q[1], q[0];, CX q[0], q[1];, CX q[1], q[0];]
```
In the case of `circ1` the synthesized circuit has two more CX gates.

This is the underlying cause of https://github.com/CQCL/pytket/issues/107 .

**Comment by cqc-alec** [comment]
> I don't think there is any peephole way of eliminating CX redundancy from the SWAP here without changing where CXs are, since the only other CX on the same pair of qubits (3, 4) is blocked by the CX on (1, 3) regardless of the direction of the SWAP. Are you confident this change was from the SWAP ordering and not another change in routing?

I did pinpoint the commit that introduced this change of behaviour, but I may have misread the true cause, as it was a moderately large refactoring. I will do some more investigation.

> Perhaps picking a different circuit for the manual might that demonstrates the intended behaviour might be the easier option.

Yes, possibly.

> The synthesis passes were intended to be lightweight, picking up the low hanging fruit of obvious redundancies. Searching for replacement patterns of >3 entangling gates or climbing up the abstraction level by recognising a logical SWAP is stretching this a little. More importantly, this is incorporated into two existing passes: `DecomposeSwapsToCXs` and `KAKDecomposition`. Since the latter completely subsumes the former, we could perhaps adapt the default passes to run `DecomposeSwapsToCXs` immediately after routing on optimisation level 1 and add `KAKDecomposition` to the post-routing optimisations for optimisation level 2? The latter will preserve connectivity but might break directedness of CXs - this isn't a problem currently as none of our CQC-maintained backends require directed CXs, but could also be fixed using `Transform::decompose_CX_directed` to flip them as needed.
> 
> In preliminary testing, comparing `FullPeepholeOptimise() >> DefaultMappingPass(device) >> SynthesiseTket() >> CliffordSimp(False) >> SynthesiseTket()` to the same sequence adding `KAKDecomposition()` before `CliffordSimp` drops CZ depth by an average of ~5% across our benchmark suite for the architectures I have run so far, so seems pretty effective

Agreed.

**Comment by cqc-alec** [comment]
@willsimmons1465 if you agree we can close this issue since #103 captures the idea above?

**Comment by willsimmons1465** [comment]
👍
