### ISSUE TITLE
Add more user options to `Backend.get_compiled_circuit`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#275]
Users need an easy way to achieve more fine-grained control over the "default" backend compilation pass. For example, the placement timeout, and any other compiler options, should be configurable through this interface.

**Comment by CalMacCQ** [comment]
I made a start on this for pytket-qiskit here https://github.com/CQCL/pytket-qiskit/pull/97 .

I was wondering if we should expose other options for the additional args in [NoiseAwarePlacement](https://cqcl.github.io/tket/pytket/api/placement.html)

<img width="548" alt="Screenshot 2023-03-28 at 17 43 46" src="https://user-images.githubusercontent.com/93673602/228310359-69397fa4-29e0-4459-a1c2-f514dc995cb1.png">

**Comment by cqc-alec** [comment]
Rather than have a lot of separate arguments we could just have an optional dictionary that gets converted to keyword arguments of the `NoiseAwarePlacement` pass.
