### ISSUE TITLE
incompatible with sympy 1.10

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/tket#280]
update pytket to work with pytket wo work with sympy 1.10, which is currently not the case.

**Comment by cqc-melf** [comment]
The workflows on the ci fail with the version in some testcase for pytket

**Comment by cqc-melf** [comment]
=================================== FAILURES ===================================
_____________________ test_QubitPauliOperator_compression ______________________

    def test_QubitPauliOperator_compression() -> None:
        qbs = [Qubit(i) for i in range(2)]
        qpsXY = QubitPauliString(qbs, [Pauli.X, Pauli.Y])
        qpsZI = QubitPauliString(qbs, [Pauli.Z, Pauli.I])
        qpsYY = QubitPauliString(qbs, [Pauli.Y, Pauli.Y])
        x = Symbol("x")
        op = QubitPauliOperator({qpsXY: 2, qpsZI: 1e-11j * x, qpsYY: 1e-11 * x + 1j})
        op.compress()
        with pytest.raises(KeyError) as errorinfo:
            term = op[qpsZI]
        assert "(Zq[0], Iq[1])" in str(errorinfo.value)
        assert op[qpsXY] == 2
        assert re(op[qpsYY]) == 0
        assert im(op[qpsYY])
>       assert op[qpsYY].subs({x: 0.001}) == 1j
E       assert 1.0*I == 1j
E        +  where 1.0*I = <bound method Basic.subs of 1.0*I*(1.0e-11*im(x) + 1.0)>({x: 0.001})
E        +    where <bound method Basic.subs of 1.0*I*(1.0e-11*im(x) + 1.0)> = 1.0*I*(1.0e-11*im(x) + 1.0).subs

qubitpaulioperator_test.py:153: AssertionError
=========================== short test summary info ============================
FAILED qubitpaulioperator_test.py::test_QubitPauliOperator_compression - asse...
======================== 1 failed, 294 passed in 56.02s ========================

**Comment by cqc-alec** [comment]
Fixed by #281 .
