### ISSUE TITLE
Typing info for compiled modules

### ISSUE THREAD

**Issue by burgholzer** [CQCL/tket#755]
Hey 👋🏼 

We are currently in the process of adding typing information to one of our projects that makes use of `pytket` under the hood.
First of all, many thanks for taking the effort to make `pytket` a typed package 👍🏼 
When running `mypy` on our code base, we stumbled upon a small issue though. We are seeing multiple warning of the sort
```python
error: Module "pytket.passes" has no
attribute "RemoveRedundancies"  [attr-defined]
    from pytket.passes import (
    ^
```
All of these warnings relate to compiled modules of tket. In the above case that would be `pytket._tket.passes`.
Do you have an idea whether that is something we can resolve on our side? The cheap solution, of course, would be to just suppress the respective warnings on our end.

I saw that a `# type: ignore` is placed on the star imports in the respective files for the compiled libraries, e.g.
https://github.com/CQCL/tket/blob/60e8aeddab40d8e87bb7404f945e226101ec0e03/pytket/pytket/passes/__init__.py#L17
I suspect this is due to the compiled libraries not being present when you perform type checking and/or because the compiled libraries themself are not typed. 
If it's the latter, this could be resolved by providing stub files (`.pyi`) for all compiled modules (see, e.g., https://mypy.readthedocs.io/en/stable/stubs.html#stub-files).

**Comment by cqc-alec** [comment]
Hi, thanks for the suggestion. This is something we would definitely like to improve. @lmondada can you comment on the stubs idea; I remember you looked into this a while back?
