### ISSUE TITLE
Circuit renderer displays the wrong angle value after conversion to qiskit and back

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/tket#763]
Small bug pointed out by @alessum.

@DNA386 

Using pytket v1.11.1
```python
from pytket import Circuit
from pytket.circuit.display import render_circuit_jupyter
from pytket.extensions.qiskit import qiskit_to_tk, tk_to_qiskit

circ1 = Circuit(2).CX(0, 1).Rz(0.2, 1).CX(0, 1)
render_circuit_jupyter(circ1)
```
The circuit diagram looks as expected 

<img width="332" alt="Screenshot 2023-03-02 at 10 35 06" src="https://user-images.githubusercontent.com/93673602/222404192-1542eac7-df0c-4498-89aa-9f6dfaa3dd04.png">

However if we convert to qiskit and then back the diagram shows the angle (0.2*pi). It seems to be picking up an extra factor of pi due to the different angle conventions of qiskit and pytket.

```python
circ2 = qiskit_to_tk(tk_to_qiskit(circ1))
render_circuit_jupyter(circ2)
```

<img width="375" alt="Screenshot 2023-03-02 at 10 39 26" src="https://user-images.githubusercontent.com/93673602/222405308-9c8867b4-1497-4587-b6ca-bda5548ce836.png">

However the underlying pytket `Circuit` has the expected angle of 0.2.

```python
print(circ2.get_commands())
```
<img width="431" alt="Screenshot 2023-03-02 at 10 41 37" src="https://user-images.githubusercontent.com/93673602/222405808-1531eb1f-c64a-48d5-a916-459a4b374f94.png">

**Comment by cqc-alec** [comment]
This is very weird, since the circuits `circ1` and `circ2` are identical (except for the names).

**Comment by CalMacCQ** [comment]
This was caused by the renderer not fully displaying the decimal expansion with a symbolic factor of pi. The entire expansion looks like Rz(0.62831.../pi) but the factor of pi wasn't apparent before. 

In the pytket 1.13.2 release the renderer has a [crop long parameters] button (on by default). If you turn this off the user can view the full expansion.

Maybe we should look into the `qiskit_to_tk` evaluating the factor of pi numerically after the conversion as the default display still looks a little misleading.
