### ISSUE TITLE
Allocation of Ancilla Qubits during Compilation

### ISSUE THREAD

**Issue by nquetschlich** [CQCL/tket#770]
Hi all,

I was wondering whether there is a possibility to allocate all unused ancilla qubits of a given device during the compilation. In qiskit, this seems to be the default case:
```python
from qiskit.providers.fake_provider import FakeWashington
from qiskit import QuantumCircuit, transpile

cmap = FakeWashington().configuration().coupling_map

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)

qc_qiskit = transpile(qc, coupling_map=cmap)
print(qc_qiskit.num_qubits)
```
returning `127` since this is the number of physical qubits IBMQ Washington offers.

For pytket, `2` is returned because this is the number of actually used qubits:

```python
from pytket.passes import PlacementPass, RoutingPass
from pytket.extensions.qiskit import qiskit_to_tk
from pytket import architecture
from pytket.placement import LinePlacement

qc_tket = qiskit_to_tk(qc)
arch = architecture.Architecture(cmap)
PlacementPass(LinePlacement(arch)).apply(qc_tket)
RoutingPass(arch).apply(qc_tket)
print(qc_tket.n_qubits)
```

I am interested whether you see any simple way to allocate the unused ancillas or whether you are planning such a feature in the future? 

The reason I am asking is that we are hosting a [quantum circuit benchmark library](https://www.cda.cit.tum.de/mqtbench/) which provides quantum circuit compiled with both the qiskit and tket compiler, and, currently, the number of qubits differs depending on the selected compiler which is not ideal in our use case.

**Comment by burgholzer** [comment]
If I may add to that: The number of qubits resulting from the compilation with TKET seems to depend on the highest qubit index used in the circuit, i.e., if the two-qubit circuit above were mapped to qubits `q79` and `q80` of the target device, the resulting circuit would contain a qubit register of size `81`.

**Comment by cqc-alec** [comment]
Pytket doesn't pad the circuit with extra qubits when routing, though you could pad the circuit with extra unused qubits before compilation.

**Comment by burgholzer** [comment]
> Yes, though the number of qubits of the pytket circuit would still be 2. (In pytket registers are not really first-class objects; whereas qubits are; registers are "mimicked" by attaching a name and index to each qubit.)

The number of qubits being two makes perfect sense to me and I get the point that tket just mimics registers.
However, it would still be kind of great to get a "consistent output" from the compilation with TKET, i.e., if I dump the resulting circuit to QASM (or translate it to a Qiskit `QuantumCircuit`) I would expect the resulting circuit to always contain registers of the same size (namely, the size of the target machine the circuit was mapped to). As it is right now, the resulting QASM for a two-qubit circuit mapped to some, let's say, 127-qubit architecture might contain a register declaration such as
```qasm
qreg q[2];
```
but it could also be
```qasm
qreg q[80];
```
or anything else; depending on where the mapper placed the qubits. That feels unnecessarily inconsistent to me.

Thanks also for your suggestion. We can use something along those lines to work around this for now on our end. But I do feel that this could also be an improvement for TKET itself.

**Comment by cqc-alec** [comment]
I've created a task #774 that should address this need; in the mean time hopefully you can work around it using https://cqcl.github.io/tket/pytket/api/circuit_class.html#pytket.circuit.Circuit.add_blank_wires .

The point about allocating an 80-qubit register in the QASM when we only use two of them is an annoying side-effect of QASM that I think we can't do much about.
