### ISSUE TITLE
Make the use of python properties/getters more consistent

### ISSUE THREAD

**Issue by yao-cqc** [CQCL/tket#814]
For instance, `Circuit.n_gates` is a property while `Circuit.n_2qb_gates` and `Circuit.n_1qb_gates` are methods. I'm also not sure whether `Circuit.depth` should be a method or a property.

**Comment by sjdilkes** [comment]
I'd agree with having them as properties!

**Comment by ss2165** [comment]
I would actually advocate for make them all methods - they all require computation, some of them non-trivial, having then as methods makes that clear.

**Comment by ss2165** [comment]
However...this is an API breaking change, one I don't think is important enough to break API contract. @cqc-alec  what do you think?

**Comment by CalMacCQ** [comment]
if we're going with methods we could go with `Circuit.get_metric()` perhaps?
 
 The word 'get' seems to communicate that it is a method rather than a property.

**Comment by cqc-alec** [comment]
Yeah I don't think we should break the API for this. We could introduce new methods though, with names prefixed by `get_` as Callum suggests.

**Comment by cqc-alec** [comment]
No specific action here; closing until we have a better idea of enhanced API.
