### ISSUE TITLE
Minor API inconsistencies with unitary boxes and `CircBox`

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/tket#858]
Firstly the `Circuit.add_unitary2qbox()` method accepts arguments like this. Same with the boxes  for 1 and 3 qubit synthesis

```
circ.add_unitary2qbox(u2box, 1, 2)
```
This differs from the usual pytket box syntax in that the qubits are specified as separate integer arguments rather than a single argument with list of integers or a list of qubits.

with `CircBox` we have 

```
circ.add_circbox(cb, [0, 1])
```

or

```
circ.add_circbox(cb, [Qubit(0), Qubit(1)])
```

`CircBox` also has .dagger as a property. With Circuit we have the `Circuit.dagger()` method. I think having .dagger as a method makes more sense as we are calculating something rather than making a query for a property.

Not sure if either of these are important enough to warrant an API change but thought I'd mention them anyway.

**Comment by cqc-alec** [comment]
This is actually for a reason: the unitart 2q box (like other unitary boxes) always takes a fixed number of qubit arguments (so can take them explicitly), whereas the circbox takes an arbitrary number (so has to take a list).

**Comment by CalMacCQ** [comment]
This makes good sense actually, thanks. Perhaps I should close this.
