### ISSUE TITLE
Docstring for `RoundAngles` pass not appearing in generated docs

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#916]
The code: https://github.com/CQCL/tket/blob/8f48ba05f1612c07a75a9cd290ba1d3ff375c9c2/pytket/binders/passes.cpp#L867

The generated docs:

![image](https://github.com/CQCL/tket/assets/54802828/b6e85375-54d3-49f4-a09d-8ec352b709cc)

Most of the docstring is missing.

**Comment by CalMacCQ** [comment]
Also an issue for [RenameQubitsPass](https://cqcl.github.io/tket/pytket/api/passes.html#pytket.passes.RenameQubitsPass) just above `RoundAngles` .

**Comment by CalMacCQ** [comment]
Found related issues in a bunch of places in the API docs.

Hopefully fixed most of the issues in https://github.com/CQCL/tket/pull/920
