### ISSUE TITLE
Get Windows CI build working with latest conan

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#992]
Currently pinning to 2.0.9: #990 .

**Comment by cqc-alec** [comment]
I think [this PR](https://github.com/conan-io/conan/pull/14705) should fix the issue. (I still don't know why we only see it on Windows though.)

**Comment by cqc-alec** [comment]
Ah, it's only showing on Windows because we build tket slightly differently there:
```
        # On windows use install + build so build directory is consistent across runs (i.e. don't build from conan cache)
        # Necessary because setting ccache base_dir doesn't currently work on windows
```

**Comment by trvto** [comment]
@cqc-alec  this can be closed now, no?

**Comment by cqc-alec** [comment]
@trvto Yes, closing.
